sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
- node_modules
branches:
   except:
   - stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set package-lock false
- npm i -g npm@^5.7.1
install:
- npm install @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: DIqweYq+Z40ko7o6lFwguQe6YwiocVcvrYmbFopeWf6PvKeaRtseltGU+31c2FlL+IaikS0r60uquGS1GLTI7LtF4mbUcwi9Tv9shxkuKwX01VbbG1RIrL+8m7UdIsrEkX6mT5BIOvE9BvkdozPW8sNL2NeMxZCkJyzRBmdBH4Vy/ZkT94nDlSu2+YfLlsxR/JQQatpTolkNqQsRdkJE04VaCpm5KNw3Tw1K4Xa7kSA5Y4rsiKxCoyxHxdri7xKnb6opM9wBOH4RcHdf2f4shsnOHkLWht15HgHjWZ5J1t4Aofftl6zjNLjw6PfvT2zGm07sEQY0JDwswNdkYfmKr3yV3KiXdvjNIFFvFoj0bm8jnyzLjpPtA1N4bii2uuPg371BjD4OopgueB6GBhX87rEiUiIpJ+VQXrYcKdef/ky9zTuNsKtXt7n15v7vdtBcPl9AvvMs2e3ftkdl9LMPWfwKD/0WLfw1gZiY+s704CFIpvdpqfM82OibkCEjoXBRyRFYa/xImab5lktRQRT8Q5Dus1ELayhM4BudLHDJAuZGhnoRRwMnCcOG3do5f6wftiM9sZHfXHzPPDjaqXRc++8pn54OINwjT+PQdO6sHtlFVyC7b+yST4hNj/dvYJL3g76SayIJ91hEJYCIXVsh6NwrR8MyDhGDQQmxuMycJHw=
  - secure: flLLDa8RwMlX9Hf9vbtO5e0vpc116s8gwXvXhnEP25WuGVM7rp74lRmDhlaVyoFLuND4f6rDeRzex4hkd7bjstlX7w++sxX66f5NMPreEm8D2Siccm5otoMdi66Xc1PsViYTrBUqtlX1HCCQKWhNEQPs2PgX+akkIZaus3DyrDzhxSMqdDsI56dJg7h9SjvMUQj0PQ9PH4Hk6ORr2mb8mTnpExD/Yyd6cBF4klxlZM2FqnfW7qd5zPLfZe9J5H+eL3powOqPwGzcDtvZb8Zcg0p8LbG88fFZSGLsRjE0R48LK8/a9fNUz1EVsbEVu8QOpU2UvwQESZmfgTyAZptblpA7qh/G0P2bu6i4QLPwLYFu3dy+hmnXmJJWgGvrP7kqn5DKMQ6fXqtXMnd7C+M7A9q+KTnHMKnkj8h+6lDNpufCzRgTExsNnMigadhRZIOOIwTYwL8vJo+OroMxIDSu4LwPn5Bkwp3QOfh6kzK/2C9iTIghDb1PErOXbDA9MvuzIFe5Gr9W/kxaOaD0hNylt/YqoMl4IzQdZGr9kYzsyjElj0U6ZWG6mnvDvhdw6zogEcgC4JMVdH3mBPz28BPGs1d7oUrXgmB/eiHq0vvakTfEZKVCOEcu3FEirqZ1VSt6iVWKO0FVX58oS6cPiEp3u59JTlOiR5JmPzOfz0Sz1T8=
