sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: DIqweYq+Z40ko7o6lFwguQe6YwiocVcvrYmbFopeWf6PvKeaRtseltGU+31c2FlL+IaikS0r60uquGS1GLTI7LtF4mbUcwi9Tv9shxkuKwX01VbbG1RIrL+8m7UdIsrEkX6mT5BIOvE9BvkdozPW8sNL2NeMxZCkJyzRBmdBH4Vy/ZkT94nDlSu2+YfLlsxR/JQQatpTolkNqQsRdkJE04VaCpm5KNw3Tw1K4Xa7kSA5Y4rsiKxCoyxHxdri7xKnb6opM9wBOH4RcHdf2f4shsnOHkLWht15HgHjWZ5J1t4Aofftl6zjNLjw6PfvT2zGm07sEQY0JDwswNdkYfmKr3yV3KiXdvjNIFFvFoj0bm8jnyzLjpPtA1N4bii2uuPg371BjD4OopgueB6GBhX87rEiUiIpJ+VQXrYcKdef/ky9zTuNsKtXt7n15v7vdtBcPl9AvvMs2e3ftkdl9LMPWfwKD/0WLfw1gZiY+s704CFIpvdpqfM82OibkCEjoXBRyRFYa/xImab5lktRQRT8Q5Dus1ELayhM4BudLHDJAuZGhnoRRwMnCcOG3do5f6wftiM9sZHfXHzPPDjaqXRc++8pn54OINwjT+PQdO6sHtlFVyC7b+yST4hNj/dvYJL3g76SayIJ91hEJYCIXVsh6NwrR8MyDhGDQQmxuMycJHw=
  - secure: flLLDa8RwMlX9Hf9vbtO5e0vpc116s8gwXvXhnEP25WuGVM7rp74lRmDhlaVyoFLuND4f6rDeRzex4hkd7bjstlX7w++sxX66f5NMPreEm8D2Siccm5otoMdi66Xc1PsViYTrBUqtlX1HCCQKWhNEQPs2PgX+akkIZaus3DyrDzhxSMqdDsI56dJg7h9SjvMUQj0PQ9PH4Hk6ORr2mb8mTnpExD/Yyd6cBF4klxlZM2FqnfW7qd5zPLfZe9J5H+eL3powOqPwGzcDtvZb8Zcg0p8LbG88fFZSGLsRjE0R48LK8/a9fNUz1EVsbEVu8QOpU2UvwQESZmfgTyAZptblpA7qh/G0P2bu6i4QLPwLYFu3dy+hmnXmJJWgGvrP7kqn5DKMQ6fXqtXMnd7C+M7A9q+KTnHMKnkj8h+6lDNpufCzRgTExsNnMigadhRZIOOIwTYwL8vJo+OroMxIDSu4LwPn5Bkwp3QOfh6kzK/2C9iTIghDb1PErOXbDA9MvuzIFe5Gr9W/kxaOaD0hNylt/YqoMl4IzQdZGr9kYzsyjElj0U6ZWG6mnvDvhdw6zogEcgC4JMVdH3mBPz28BPGs1d7oUrXgmB/eiHq0vvakTfEZKVCOEcu3FEirqZ1VSt6iVWKO0FVX58oS6cPiEp3u59JTlOiR5JmPzOfz0Sz1T8=
  - secure: Xwq0fQ4Qfnd13jn6X9mD+yy5r8+uuCquOE3sDjKYWABMpswZ25EDC5kBCdmJLV6Je0Di+3+cHP7kxH+5KmAFwpUvcQRZkHh+K4YjO4NmuvJ3VJqZUdiZn7+SwiedknRW3AODMHbAwSZ3RbhU5yxw+eCYokF6D0BbOvZhw36J0jN0B6Ado4Q/RaiTIjb/OSLWo25aAfXdFEtcfA00hyQycyNNTOTMXOfC2C3M1bfGK6T7AmX4K7Hyfip4tdcS7mYeDtfAlLdJKlPwR9ub3KMuzDqb7sVPqvD5Ex9kxEAraNQ9NTKN2MrgZMeJux/f6PTHWGQfslaZHfyBNVlkTgd526r1vYcXcyTSaM4cDvvxRyVYmKt5ybsJ+Pscxq3P4FF4j1nRnFWQelyK1I4/MuZHG77mHOzf9ReQkDjKqWqsKphzlgiL7YNhqrxVvgisTnrS6Kroc8ImdKbP2B6aOD7xewsdrDZt0VhE0w890Sk8YWx6JcYgwA8tMoVDQPbSlSWGMrvhfaQMXbI39V0bYNN0UvqdI7SK1zSsnTRYYJu0Zk7nVmV2SwbZ99CHqumOVPcPgKdQw5IZ44DeZbeKzpoUS0J01JYB+QDTrxgz6DU10xSUn2OLy5Z91zBn9JU6DWsT1OS6Ydix8AGv2ub3AfBweO6bkUKVYJtJmhMpRpj+MGk=
